/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iudigital.gestionfuncionario.vista;

import com.iudigital.gestionfuncionario.controller.FuncionarioController;
import com.iudigital.gestionfuncionario.domain.Funcionario;

import java.sql.SQLException;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cleum
 */
public class main extends javax.swing.JFrame {

    private final FuncionarioController funFuncionarioController;

    private final static String[] COLUMNS = {"IDFUNCIONARIO", "TIPOIDENTIFICACION", "IDENTIFICACION",
        "NOMBRES", "APELLIDOS", "ESTADOCIVIL", "FKIDGENERO", "DIRECCION", "TELEFONO", "FECHANACIMIENTO"};
    private final static String SELECCIONE = "--SELECCIONE--";
    private Object JoptionPane;

    public main() {
        initComponents();
        txtidfuncionario.setEditable(false);
        funFuncionarioController = new FuncionarioController();
        listFuncionarios();
        addListener();
    }

    private void listFuncionarios() {
        cbxFuncionarios.removeAllItems();
        Funcionario funcionario1 = new Funcionario();
        funcionario1.setNOMBRES(SELECCIONE);
        funcionario1.setAPELLIDOS("");
        cbxFuncionarios.addItem(funcionario1);
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        for (String COLUMN : COLUMNS) {
            defaultTableModel.addColumn(COLUMN);

        }
        TblFUNCIONARIOS.setModel(defaultTableModel);

        try {
            List<Funcionario> funcionarios = funFuncionarioController.obtenerFuncionario();
            if (funcionarios.isEmpty()) {
                return;
            }
            defaultTableModel.setRowCount((funcionarios.size()));
            int row = 0;
            for (Funcionario funcionario : funcionarios) {
                defaultTableModel.setValueAt(funcionario.getIDFUNCIONARIOS(), row, 0);
                defaultTableModel.setValueAt(funcionario.getTIPOIDENTIFICACION(), row, 1);
                defaultTableModel.setValueAt(funcionario.getIDENTIFICACION(), row, 2);
                defaultTableModel.setValueAt(funcionario.getNOMBRES(), row, 3);
                defaultTableModel.setValueAt(funcionario.getAPELLIDOS(), row, 4);
                defaultTableModel.setValueAt(funcionario.getESTADOCIVIL(), row, 5);
                defaultTableModel.setValueAt(funcionario.getFKIDGENERO(), row, 6);
                defaultTableModel.setValueAt(funcionario.getDIRECCION(), row, 7);
                defaultTableModel.setValueAt(funcionario.getTELEFONO(), row, 8);
                defaultTableModel.setValueAt(funcionario.getFECHANACIMIENTO(), row, 8);
                row++;

                cbxFuncionarios.addItem(funcionario);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void addListener() {
        cbxFuncionarios.addItemListener(event -> {
            Funcionario seledtedFuncionnario = (Funcionario) event.getItem();
            if (seledtedFuncionnario.getNOMBRES().equals(SELECCIONE)) {
                txtidfuncionario.setText("");
                txtEdittipodocumento.setText("");
                txteditdocumento.setText("");
                txteditnombre.setText("");
                txteditapellidos.setText("");
                txteditestadocivil.setText("");
                txteditgenero.setText("");
                txtedtidirecion.setText("");
                txtedittelefono.setText("");
                txteditfechanacimiento.setText("");
            } else {
                txtidfuncionario.setText(String.valueOf(seledtedFuncionnario.getIDFUNCIONARIOS()));
                txtEdittipodocumento.setText(seledtedFuncionnario.getTIPOIDENTIFICACION());
                txteditdocumento.setText(seledtedFuncionnario.getIDENTIFICACION());
                txteditnombre.setText(seledtedFuncionnario.getNOMBRES());
                txteditapellidos.setText(seledtedFuncionnario.getAPELLIDOS());
                txteditestadocivil.setText(seledtedFuncionnario.getESTADOCIVIL());
                txteditgenero.setText(String.valueOf(seledtedFuncionnario.getFKIDGENERO());
                txtedtidirecion.setText(seledtedFuncionnario.getDIRECCION());
                txtedtidirecion.setText(seledtedFuncionnario.getTELEFONO());
                txteditfechanacimiento.setText(seledtedFuncionnario.getFECHANACIMIENTO());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbtipoidentificacion = new javax.swing.JLabel();
        txtTIPOIDENTIFICACION = new javax.swing.JTextField();
        lbidentificacion = new javax.swing.JLabel();
        txtIDENTIFICACION = new javax.swing.JTextField();
        lbnombres = new javax.swing.JLabel();
        txtNOMBRES = new javax.swing.JTextField();
        txtAPELLIDOS = new javax.swing.JTextField();
        lbestadocivil = new javax.swing.JLabel();
        txtESTADOCIVIL = new javax.swing.JTextField();
        lbgenero = new javax.swing.JLabel();
        txtFKIDGENERO = new javax.swing.JTextField();
        lbdireccion = new javax.swing.JLabel();
        txtDIRECCION = new javax.swing.JTextField();
        lbtelefono = new javax.swing.JLabel();
        txtTELEFONO = new javax.swing.JTextField();
        txtFECHANACIMIENTO = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        lbapellidos = new javax.swing.JLabel();
        lbfechanacimiento = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFUNCIONARIOS = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cbxFuncionarios = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEdittipodocumento = new javax.swing.JTextField();
        txteditdocumento = new javax.swing.JTextField();
        txteditnombre = new javax.swing.JTextField();
        txteditapellidos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtidfuncionario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txteditestadocivil = new javax.swing.JTextField();
        txteditgenero = new javax.swing.JTextField();
        txtedtidirecion = new javax.swing.JTextField();
        txtedittelefono = new javax.swing.JTextField();
        txteditfechanacimiento = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblFUNCIONARIOS = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("GESTION DE FUNCIONARIOS");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 160, 20));

        jTPane1.setName(""); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Favor digite los siguientes campos"));

        lbtipoidentificacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtipoidentificacion.setText("TIPO IDENTIFICACION");

        txtTIPOIDENTIFICACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTIPOIDENTIFICACIONActionPerformed(evt);
            }
        });

        lbidentificacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbidentificacion.setText("IDENTIFICACION");

        lbnombres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbnombres.setText("NOMBRES");

        lbestadocivil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbestadocivil.setText("ESTADO CIVIL");

        lbgenero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbgenero.setText("GENERO");

        lbdireccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbdireccion.setText("DIRECCIÓN");

        lbtelefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtelefono.setText("TELEFONO");

        txtFECHANACIMIENTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFECHANACIMIENTOActionPerformed(evt);
            }
        });

        btnCrear.setText("Guardar");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        lbapellidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbapellidos.setText("APELLIDOS");

        lbfechanacimiento.setText("FECHA NACIMIENTO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbtipoidentificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(txtTIPOIDENTIFICACION))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDENTIFICACION, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbestadocivil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtESTADOCIVIL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbgenero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFKIDGENERO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDIRECCION)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtTELEFONO, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                            .addComponent(lbtelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFECHANACIMIENTO)
                            .addComponent(lbfechanacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNOMBRES, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(lbnombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtAPELLIDOS)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnCrear)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtipoidentificacion)
                    .addComponent(lbidentificacion)
                    .addComponent(lbnombres)
                    .addComponent(lbapellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTIPOIDENTIFICACION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDENTIFICACION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNOMBRES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAPELLIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtelefono)
                    .addComponent(lbdireccion)
                    .addComponent(lbgenero)
                    .addComponent(lbestadocivil)
                    .addComponent(lbfechanacimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFECHANACIMIENTO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTELEFONO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDIRECCION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFKIDGENERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtESTADOCIVIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnCrear)
                .addContainerGap())
        );

        jLabel2.setText("jLabel2");

        tblFUNCIONARIOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblFUNCIONARIOS);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(174, 174, 174)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTPane1.addTab("Crear", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Actualizar o Eliminar un Funcionario"));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TIPO DOCUMENTO");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DOCUMENTO");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("NOMBRES");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("APELLIDOS");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ESTADO CIVIL");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ID");

        txtidfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidfuncionarioActionPerformed(evt);
            }
        });

        jLabel11.setText("TELEFONO");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("FECHA NACIMIENTO");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("GENERO");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("DIRECCION");

        txtedtidirecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtedtidirecionActionPerformed(evt);
            }
        });

        txteditfechanacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteditfechanacimientoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setText("Actualizar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel10.setText("funcionarios");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(596, 596, 596))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(txteditestadocivil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txteditgenero, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnEliminar)
                                .addGap(60, 60, 60)
                                .addComponent(btnEditar))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtedtidirecion)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtedittelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(txteditfechanacimiento))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtidfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEdittipodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txteditdocumento)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txteditnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txteditapellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdittipodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txteditdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txteditnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txteditapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtedittelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtedtidirecion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txteditgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txteditestadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txteditfechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        TblFUNCIONARIOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(TblFUNCIONARIOS);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel5.getAccessibleContext().setAccessibleName("Actualizar o Eliminar Funcionarios");
        jPanel5.getAccessibleContext().setAccessibleDescription("");

        jTPane1.addTab("Actualizar", jPanel4);

        getContentPane().add(jTPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFECHANACIMIENTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFECHANACIMIENTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFECHANACIMIENTOActionPerformed

    private void txtTIPOIDENTIFICACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTIPOIDENTIFICACIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTIPOIDENTIFICACIONActionPerformed

    private void txteditfechanacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteditfechanacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txteditfechanacimientoActionPerformed

    private void txtedtidirecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtedtidirecionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtedtidirecionActionPerformed

    private void txtidfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidfuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidfuncionarioActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (txtTIPOIDENTIFICACION.getText().trim().length() == 0) {
            JoptionPane.showMessageDialog(null, "selecione un funcionario");
            txtTIPOIDENTIFICACION.requestFocus();
            return;
        }
        int opt = JoptionPane.show.ConfirmDialog(null, "esta seguro de eliminar el funcionario",
                "confirmar la salida", JoptionPane.YES_NO_OPTION, JoptionPane.QUESTION_MESSAGE);
        if (opt == 0) {
            try {
                funFuncionarioController.eliminarFuncionario(Integer.parseInt(txtidfuncionario.getText()));

                txtidfuncionario.setText("");
                txtEdittipodocumento.setText("");
                txteditdocumento.setText("");
                txteditnombre.setText("");
                txteditapellidos.setText("");
                txteditestadocivil.setText("");
                txteditgenero.setText("");
                txtedtidirecion.setText("");
                txtedittelefono.setText("");
                txteditfechanacimiento.setText("");
            } catch (SQLException ex) {
                ex.printStackTrace()
            }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        if (txtTIPOIDENTIFICACION.getText().trim().length() == 0) {
            JoptionPane.showMessageDialog(null, "Digite el Tipo de identificacion");
            txtTIPOIDENTIFICACION.RequestFocus();
            return;
        }
        if (txtIDENTIFICACION.getText().trim().length() == 0) {
            JoptionPane.showMessageDialog(null, "Digite el numero de identificacion");
            txtIDENTIFICACION.RequestFocus();
            return;
        }
        if (txtNOMBRES.getText().trim().length() == 0) {
            JoptionPane.showMessageDialog(null, "DIGITE el NOMBRE");
            txtNOMBRES.RequestFocus();
            return;
        }
        if (txtAPELLIDOS.getText().trim().length() == 0) {
            JoptionPane.showMessageDialog(null, "DIGITE el APELLIDO");
            txtAPELLIDOS.RequestFocus();
            return;
        }
        if (txtESTADOCIVIL.getText().trim().length() == 0) {
            JoptionPane.showMessageDialog(null, "DIGITE el ESTADO CIVIL");
            txtESTADOCIVIL.RequestFocus();
            return;
        }
        if (txtFKIDGENERO.getText().trim().length() == 0) {
            JoptionPane.showMessageDialog(null, "DV EL GENERO");
            txtFKIDGENERO.RequestFocus();
            return;
        }
        if (txtDIRECCION.getText().trim().length() == 0) {
            JoptionPane.showMessageDialog(null, "DIGITE LA DIRECCION");
            txtDIRECCION.RequestFocus();
            return;
        }
        if (txtTELEFONO.getText().trim().length() == 0) {
            JoptionPane.showMessageDialog(null, "DIGITE el TELEFONO");
            txtTELEFONO.RequestFocus();
            return;
        }
        if (txtFECHANACIMIENTO.getText().trim().length() == 0) {
            JoptionPane.showMessageDialog(null, "DIGITE LA FECHA DE NACIMIENTO");
            txtFECHANACIMIENTO.RequestFocus();
            return;
        }
        try {
            Funcionario funcionario = new Funcionario();
            funcionario.setTIPOIDENTIFICACION(txtTIPOIDENTIFICACION.getText().trim());
            funcionario.setIDENTIFICACION(txtIDENTIFICACION.getText().trim());
            funcionario.setNOMBRES(txtNOMBRES.getText().trim());
            funcionario.setAPELLIDOS(txtAPELLIDOS.getText().trim());
            funcionario.setESTADOCIVIL(txtESTADOCIVIL.getText().trim());
            funcionario.setFKIDGENERO(txtFKIDGENERO.getText().trim());
            funcionario.setDIRECCION(txtDIRECCION.getText().trim());
            funcionario.setTELEFONO(txtTELEFONO.getText().trim());
            funcionario.setFECHANACIMIENTO(txtFECHANACIMIENTO.getText().trim());

            funFuncionarioController.crear(funcionario);
            txtTIPOIDENTIFICACION.setText("");
            txtIDENTIFICACION.setText("");
            txtNOMBRES.setText("");
            txtAPELLIDOS.setText("");
            txtESTADOCIVIL.setText("");
            txtFKIDGENERO.setText("");
            txtDIRECCION.setText("");
            txtTELEFONO.setText("");
            txtFECHANACIMIENTO.setText("");
            listFuncionarios();
            JoptionPane.showMessageDialog(null, "carro fue creado ");
        } catch (SQLException ex) {
            ex.printStackTrace()
            JoptionPane.showMessageDialog(null, "carro no fue creado ");
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (txtidfuncionario.getText().trim().length() == 0) {
            JoptionPane.showMessageDialog(null, "Digite un funcionario ");
            txtidfuncionario.RequestFocus();
            return;
        }
        if (txtEdittipodocumento.getText().trim().length() == 0) {
            JoptionPane.showMessageDialog(null, "Digite el Tipo de identificacion");
            txtxtEdittipodocumento.RequestFocus();
            return;
        }
        if (txteditdocumento.getText().trim().length() == 0) {
            JoptionPane.showMessageDialog(null, "Digite el numero de identificacion");
            txteditdocumento.RequestFocus();
            return;
        }
        if (txteditnombre.getText().trim().length() == 0) {
            JoptionPane.showMessageDialog(null, "DIGITE el NOMBRE");
            txteditnombre.RequestFocus();
            return;
        }
        if (txteditapellidos.getText().trim().length() == 0) {
            JoptionPane.showMessageDialog(null, "DIGITE el APELLIDO");
            txteditapellidos.RequestFocus();
            return;
        }
        if (txteditestadocivil.getText().trim().length() == 0) {
            JoptionPane.showMessageDialog(null, "DIGITE el ESTADO CIVIL");
            txteditestadocivil.RequestFocus();
            return;
        }
        if (txteditgenero.getText().trim().length() == 0) {
            JoptionPane.showMessageDialog(null, "DIGITE 1 masculino  2 femenino 3 otros");
            txteditgenero.RequestFocus();
            return;
        }
        if (txtedtidirecion.getText().trim().length() == 0) {
            JoptionPane.showMessageDialog(null, "DIGITE LA DIRECCION");
            txtedtidirecion.RequestFocus();
            return;
        }
        if (txtedittelefono.getText().trim().length() == 0) {
            JoptionPane.showMessageDialog(null, "DIGITE el TELEFONO");
            txtedittelefono.RequestFocus();
            return;
        }
        if (txteditfechanacimiento.getText().trim().length() == 0) {
            JoptionPane.showMessageDialog(null, "DIGITE LA FECHA DE NACIMIENTO");
            txteditfechanacimiento.RequestFocus();
            return;
        }

        Funcionario funcionario = new Funcionario();
        funcionario.setTIPOIDENTIFICACION(txtEdittipodocumento.getText().trim());
        funcionario.setIDENTIFICACION(txteditdocumento.getText().trim());
        funcionario.setNOMBRES(txteditnombre.getText().trim());
        funcionario.setAPELLIDOS(txteditapellidos.getText().trim());
        funcionario.setESTADOCIVIL(txteditestadocivil.getText().trim());
        funcionario.setFKIDGENERO(txteditgenero.getText().trim());
        funcionario.setDIRECCION(txtedtidirecion.getText().trim());
        funcionario.setTELEFONO(txtedittelefono.getText().trim());
        funcionario.setFECHANACIMIENTO(txteditfechanacimiento.getText().trim());
        int opt = JoptionPane.showConfirmDialog(null,
                "desea actualisar el carro", "confirmar la salida",
                JoptionPane.YES_NO_OPTION, JoptionPane.QUESTION_MESSAGE);
        if (opt == 0) {
            try {
                funFuncionarioController.actualizarFuncionario(Integer.parseInt(txtidfuncionario.getText()), funcionario);
                txtidfuncionario.setText("");
                txtEdittipodocumento.setText("");
                txteditdocumento.setText("");
                txteditnombre.setText("");
                txteditapellidos.setText("");
                txteditestadocivil.setText("");
                txteditgenero.setText("");
                txtedtidirecion.setText("");
                txtedittelefono.setText("");
                txteditfechanacimiento.setText("");

            } catch (SQLException ex) {
                ex.printStackTrace();
                JoptionPane.showMessageDialog(null, "carro no fue actualisado ");
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblFUNCIONARIOS;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<Funcionario> cbxFuncionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbapellidos;
    private javax.swing.JLabel lbdireccion;
    private javax.swing.JLabel lbestadocivil;
    private javax.swing.JLabel lbfechanacimiento;
    private javax.swing.JLabel lbgenero;
    private javax.swing.JLabel lbidentificacion;
    private javax.swing.JLabel lbnombres;
    private javax.swing.JLabel lbtelefono;
    private javax.swing.JLabel lbtipoidentificacion;
    private javax.swing.JTable tblFUNCIONARIOS;
    private javax.swing.JTextField txtAPELLIDOS;
    private javax.swing.JTextField txtDIRECCION;
    private javax.swing.JTextField txtESTADOCIVIL;
    private javax.swing.JTextField txtEdittipodocumento;
    private javax.swing.JTextField txtFECHANACIMIENTO;
    private javax.swing.JTextField txtFKIDGENERO;
    private javax.swing.JTextField txtIDENTIFICACION;
    private javax.swing.JTextField txtNOMBRES;
    private javax.swing.JTextField txtTELEFONO;
    private javax.swing.JTextField txtTIPOIDENTIFICACION;
    private javax.swing.JTextField txteditapellidos;
    private javax.swing.JTextField txteditdocumento;
    private javax.swing.JTextField txteditestadocivil;
    private javax.swing.JTextField txteditfechanacimiento;
    private javax.swing.JTextField txteditgenero;
    private javax.swing.JTextField txteditnombre;
    private javax.swing.JTextField txtedittelefono;
    private javax.swing.JTextField txtedtidirecion;
    private javax.swing.JTextField txtidfuncionario;
    // End of variables declaration//GEN-END:variables

    private static class J0ptionPane {

        public J0ptionPane() {
        }
    }
}
